#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$:.unshift(lib_path) if !$:.include?(lib_path)
require "queen"

begin
  Queen::CLI.run(*ARGV)
rescue Queen::CLI::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end
